# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from .dependency_conditionality_type import DependencyConditionalityType
from .file import File
from .package import Package
from .sbom import Sbom
from .sbom_type import SbomType
from .snippet import Snippet
from .software_artifact import SoftwareArtifact
from .software_dependency_link_type import SoftwareDependencyLinkType
from .software_dependency_relationship import SoftwareDependencyRelationship
from .software_purpose import SoftwarePurpose
