# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!

from ..core import Agent, CreationInfo, Element, ExternalIdentifier, ExternalReference, IntegrityMethod, RelationshipCompleteness, RelationshipType
from ..security import VexVulnAssessmentRelationship
from beartype.typing import List, Optional
from datetime import datetime
from spdx_tools.common.typing.type_checks import check_types_and_set_values

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties


@dataclass_with_properties
class VexFixedVulnAssessmentRelationship(VexVulnAssessmentRelationship):
    """
    VexFixedVulnAssessmentRelationship links a vulnerability to a number of elements representing VEX products where a
    vulnerability has been fixed and are no longer affected. It represents the VEX fixed status.

    **Constraints**

    When linking elements using a VexFixedVulnAssessmentRelationship, the following requirements must be observed:

    - Elements linked with a VulnVexFixedAssessmentRelationship are constrained to using the fixedIn relationship type.
    - The from: end of the relationship must ve a /Security/Vulnerability classed element.

    **Syntax**

    ```json
    {
      "@type": "VexFixedVulnAssessmentRelationship",
      "@id": "urn:spdx.dev:vex-fixed-in-1",
      "relationshipType": "fixedIn",
      "from": "urn:spdx.dev:vuln-cve-2020-28498",
      "to": ["urn:product-acme-application-1.3"],
      "assessedElement": "urn:npm-elliptic-6.5.4",
      "suppliedBy": ["urn:spdx.dev:agent-jane-doe"],
      "publishedTime": "2021-03-09T11:04:53Z"
    }
    ```
    """

    def __init__(
        self,
        spdx_id: str,
        creation_info: CreationInfo,
        from_element: Element,
        relationship_type: RelationshipType,
        name: Optional[str] = None,
        summary: Optional[str] = None,
        description: Optional[str] = None,
        comment: Optional[str] = None,
        verified_using: List[IntegrityMethod] = None,
        external_reference: List[ExternalReference] = None,
        external_identifier: List[ExternalIdentifier] = None,
        extension: Optional[str] = None,
        to: List[Element] = None,
        completeness: Optional[RelationshipCompleteness] = None,
        start_time: Optional[datetime] = None,
        end_time: Optional[datetime] = None,
        assessed_element: Optional[Element] = None,
        published_time: Optional[datetime] = None,
        supplied_by: Optional[Agent] = None,
        modified_time: Optional[datetime] = None,
        withdrawn_time: Optional[datetime] = None,
        vex_version: Optional[str] = None,
        status_notes: Optional[str] = None,
    ):
        verified_using = [] if verified_using is None else verified_using
        external_reference = [] if external_reference is None else external_reference
        external_identifier = [] if external_identifier is None else external_identifier
        to = [] if to is None else to
        check_types_and_set_values(self, locals())
