# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from abc import abstractmethod
from datetime import datetime

from beartype.typing import Optional

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties

from ..core import Relationship


@dataclass_with_properties
class VulnAssessmentRelationship(Relationship):
    """
    VulnAssessmentRelationship is the ancestor class common to all vulnerability assessment relationships. It factors
    out the common properties shared by them. External property restriction on /Core/Relationship/to: minCount: 1
    """

    assessed_element: Optional[str] = None
    """
    Specifies subpackages, files or snippets referenced by a security assessment to specify the precise location where
    a vulnerability was found.
    """
    published_time: Optional[datetime] = None
    """
    Specifies the time when a vulnerability was first published.
    """
    supplied_by: Optional[str] = None
    """
    Identify the actual distribution source for the vulnerability assessment relationship being referenced.
    """
    modified_time: Optional[datetime] = None
    """
    Specifies a time when a vulnerability assessment was last modified.
    """
    withdrawn_time: Optional[datetime] = None
    """
    Specified the time and date when a vulnerability was withdrawn.
    """

    @abstractmethod
    def __init__(self):
        pass
