# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from abc import abstractmethod

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties

from ..licensing.any_license_info import AnyLicenseInfo


@dataclass_with_properties
class ExtendableLicense(AnyLicenseInfo):
    """
    The WithAdditionOperator can have a License or an OrLaterOperator as the license property value. This class is used
    for the value.
    """

    @abstractmethod
    def __init__(self):
        pass
