# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from .agent import Agent
from .annotation import Annotation
from .annotation_type import AnnotationType
from .artifact import Artifact
from .bom import Bom
from .bundle import Bundle
from .creation_info import CreationInfo
from .element import Element
from .element_collection import ElementCollection
from .external_identifier import ExternalIdentifier
from .external_identifier_type import ExternalIdentifierType
from .external_map import ExternalMap
from .external_reference import ExternalReference
from .external_reference_type import ExternalReferenceType
from .hash import Hash
from .hash_algorithm import HashAlgorithm
from .integrity_method import IntegrityMethod
from .lifecycle_scope_type import LifecycleScopeType
from .lifecycle_scoped_relationship import LifecycleScopedRelationship
from .organization import Organization
from .person import Person
from .positive_integer_range import PositiveIntegerRange
from .profile_identifier_type import ProfileIdentifierType
from .relationship import Relationship
from .relationship_completeness import RelationshipCompleteness
from .relationship_type import RelationshipType
from .software_agent import SoftwareAgent
from .spdx_document import SpdxDocument
from .tool import Tool
