# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from enum import Enum, auto

from beartype.typing import Optional


class AnnotationType(Enum):
    """
    AnnotationType specifies the type of an annotation.
    """

    OTHER = auto()
    """
    Used to store extra information about an Element which is not part of a Review (e.g. extra information provided
    during the creation of the Element).
    """
    REVIEW = auto()
    """
    Used when someone reviews the Element.
    """

    def __str__(self) -> str:
        if self == AnnotationType.OTHER:
            return "other"
        if self == AnnotationType.REVIEW:
            return "review"
        return "unknown"

    @staticmethod
    def from_str(value: str) -> Optional["AnnotationType"]:
        if value == "other":
            return AnnotationType.OTHER
        if value == "review":
            return AnnotationType.REVIEW
        return None
