# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from abc import ABC
from dataclasses import field
from datetime import datetime

from beartype.typing import List, Optional
from semantic_version import Version

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties
from spdx_tools.common.typing.type_checks import check_types_and_set_values

from ..core.profile_identifier_type import ProfileIdentifierType


@dataclass_with_properties
class CreationInfo(ABC):
    """
    The CreationInfo provides information about who created the Element, and when and how it was created.

    The dateTime created is often the date of last change (e.g., a git commit date), not the date when the SPDX data
    was created, as doing so supports reproducible builds.
    """

    spec_version: Version = None
    """
    The specVersion provides a reference number that can be used to understand how to parse and interpret an Element.
    It will enable both future changes to the specification and to support backward compatibility. The major version
    number shall be incremented when incompatible changes between versions are made (one or more sections are created,
    modified or deleted). The minor version number shall be incremented when backwards compatible changes are made.

    Here, parties exchanging information in accordance with the SPDX specification need to provide 100% transparency as
    to which SPDX specification version such information is conforming to.
    """
    comment: Optional[str] = None
    """
    A comment is an optional field for creators of the Element to provide comments to the readers/reviewers of the
    document.
    """
    created: Optional[datetime] = None
    """
    Created is a date that identifies when the Element was originally created. The time stamp can serve as an
    indication as to whether the analysis needs to be updated. This is often the date of last change (e.g., a git
    commit date), not the date when the SPDX data was created, as doing so supports reproducible builds.
    """
    created_by: List[str] = field(default_factory=list)
    """
    CreatedBy identifies who or what created the Element. The generation method will assist the recipient of the
    Element in assessing the general reliability/accuracy of the analysis information.
    """
    created_using: List[str] = field(default_factory=list)
    """
    CreatedUsing identifies the tooling that was used during the creation of the Element. The generation method will
    assist the recipient of the Element in assessing the general reliability/accuracy of the analysis information.
    """
    profile: List[ProfileIdentifierType] = field(default_factory=list)
    """
    This field provides information about which profiles the Element belongs to.
    """
    data_license: Optional[str] = None
    """
    The data license provides the license under which the SPDX documentation of the Element can be used. This is to
    alleviate any concern that content (the data or database) in an SPDX file is subject to any form of intellectual
    property right that could restrict the re-use of the information or the creation of another SPDX file for the same
    project(s). This approach avoids intellectual property and related restrictions over the SPDX file, however
    individuals can still contract with each other to restrict release of specific collections of SPDX files (which map
    to software bill of materials) and the identification of the supplier of SPDX files. Compliance with this document
    includes populating the SPDX fields therein with data related to such fields ("SPDX-Metadata"). This document
    contains numerous fields where an SPDX file creator may provide relevant explanatory text in SPDX-Metadata. Without
    opining on the lawfulness of "database rights" (in jurisdictions where applicable), such explanatory text is
    copyrightable subject matter in most Berne Convention countries. By using the SPDX specification, or any portion
    hereof, you hereby agree that any copyright rights (as determined by your jurisdiction) in any SPDX-Metadata,
    including without limitation explanatory text, shall be subject to the terms of the Creative Commons CC0 1.0
    Universal license. For SPDX-Metadata not containing any copyright rights, you hereby agree and acknowledge that the
    SPDX-Metadata is provided to you “as-is” and without any representations or warranties of any kind concerning the
    SPDX-Metadata, express, implied, statutory or otherwise, including without limitation warranties of title,
    merchantability, fitness for a particular purpose, non-infringement, or the absence of latent or other defects,
    accuracy, or the presence or absence of errors, whether or not discoverable, all to the greatest extent permissible
    under applicable law.
    """

    def __init__(
        self,
        spec_version: Version,
        created_by: List[str],
        profile: List[ProfileIdentifierType],
        comment: Optional[str] = None,
        created: Optional[datetime] = None,
        created_using: List[str] = None,
        data_license: Optional[str] = None,
    ):
        created_using = [] if created_using is None else created_using
        check_types_and_set_values(self, locals())
