# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!

from spdx_tools.common.typing.type_checks import check_types_and_set_values

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties


@dataclass_with_properties
class DateTime(str):
    """
    A Datetime is a string representation of a specific date and time. It has resolution of seconds and is always
    expressed in UTC timezone. The specific format is one of the most commonly used ISO-8601 formats. Format
    restriction: pattern: ^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\dZ$
    """

    def __init__(
        self,
    ):
        check_types_and_set_values(self, locals())
