# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!

from abc import ABC
from beartype.typing import Optional
from spdx_tools.common.typing.type_checks import check_types_and_set_values

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties


@dataclass_with_properties
class DictionaryEntry(ABC):
    """
    The class used for implementing a generic string mapping (also known as associative array, dictionary, or hash map)
    in SPDX. Each DictionaryEntry contains a key-value pair which maps the key to its associated value. To implement a
    dictionary, this class is to be used in a collection with unique keys.
    """
    key: str
    """
    A key used in generic a key-value pair. A key-value pair can be used to implement a dictionary which associates a
    key with a value.
    """
    value: Optional[str] = None
    """
    A value used in a generic key-value pair. A key-value pair can be used to implement a dictionary which associates a
    key with a value.
    """

    def __init__(
        self,
        key: str,
        value: Optional[str] = None,
    ):
        check_types_and_set_values(self, locals())
