# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!

from ..core import CreationInfo, Element, ExternalIdentifier, ExternalMap, ExternalReference, IntegrityMethod
from abc import abstractmethod
from beartype.typing import List, Optional
from dataclasses import field

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties


@dataclass_with_properties
class ElementCollection(Element):
    """
    An SpdxCollection is a collection of Elements, not necessarily with unifying context.
    """
    element: List[str] = field(default_factory=list)
    """
    This field refers to one or more Elements that are part of an ElementCollection.
    """
    root_element: List[str] = field(default_factory=list)
    """
    A rootElement of a collection is the top level Element from which all other Elements are reached via relationships.
    """
    imports: List[ExternalMap] = field(default_factory=list)
    """
    Imports provides an ExternalMap of Element identifiers that are used within a document but defined external to that
    document.
    """

    @abstractmethod
    def __init__(self):
        pass
