# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!

from ..core import ExternalReferenceType, MediaType
from abc import ABC
from beartype.typing import List, Optional
from dataclasses import field
from spdx_tools.common.typing.type_checks import check_types_and_set_values

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties


@dataclass_with_properties
class ExternalReference(ABC):
    """
    An External Reference points to a resource outside the scope of the SPDX-3.0 content that provides additional
    characteristics of an Element.
    """
    external_reference_type: Optional[ExternalReferenceType] = None
    """
    An externalReferenceType specifies the type of the external reference.
    """
    locator: List[str] = field(default_factory=list)
    """
    A locator provides the location of an external reference.
    """
    content_type: Optional[MediaType] = None
    """
    ContentType specifies the media type of an Element.
    """
    comment: Optional[str] = None
    """
    A comment is an optional field for creators of the Element to provide comments to the readers/reviewers of the
    document.
    """

    def __init__(
        self,
        external_reference_type: Optional[ExternalReferenceType] = None,
        locator: List[str] = None,
        content_type: Optional[MediaType] = None,
        comment: Optional[str] = None,
    ):
        locator = [] if locator is None else locator
        check_types_and_set_values(self, locals())
