# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from abc import ABC, abstractmethod

from beartype.typing import Optional

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties


@dataclass_with_properties
class IntegrityMethod(ABC):
    """
    An IntegrityMethod provides an independently reproducible mechanism that permits verification of a specific Element
    that correlates to the data in this SPDX document. This identifier enables a recipient to determine if anything in
    the original Element has been changed and eliminates confusion over which version or modification of a specific
    Element is referenced.
    """

    comment: Optional[str] = None
    """
    A comment is an optional field for creators of the Element to provide comments to the readers/reviewers of the
    document.
    """

    @abstractmethod
    def __init__(self):
        pass
