# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!

from abc import ABC
from spdx_tools.common.typing.type_checks import check_types_and_set_values

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties


@dataclass_with_properties
class NamespaceMap(ABC):
    """
    A namespace map allows the creator of a collection of Elements to use shorter identifiers ("prefixes") instead of
    URIs to provide a more human-readable and smaller serialized representation of the Elements.
    """
    prefix: str
    """
    A prefix is a substitute for a URI.
    """
    namespace: str
    """
    A namespace provides an unambiguous mechanism for other documents to reference Elements within this document.
    """

    def __init__(
        self,
        prefix: str,
        namespace: str,
    ):
        check_types_and_set_values(self, locals())
