# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!

from .any_license_info import AnyLicenseInfo
from .custom_license import CustomLicense
from .custom_license_addition import CustomLicenseAddition
from .license import License
from .license_addition import LicenseAddition
from .license_expression import LicenseExpression
from .listed_license import ListedLicense
from .listed_license_exception import ListedLicenseException
from .or_later_operator import OrLaterOperator
from .with_addition_operator import WithAdditionOperator
