# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from beartype.typing import Optional

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties
from spdx_tools.common.typing.type_checks import check_types_and_set_values

from ..licensing import License


@dataclass_with_properties
class ListedLicense(License):
    """
    A ListedLicense represents a License that is listed on the SPDX License List at https://spdx.org/licenses.
    """

    list_version_added: Optional[str] = None
    """
    A listVersionAdded for a ListedLicense or ListedLicenseException on the SPDX License List specifies which version
    release of the License List was the first one in which it was included.
    """
    deprecated_version: Optional[str] = None
    """
    A deprecatedVersion for a ListedLicense or ListedLicenseException on the SPDX License List specifies which version
    release of the License List was the first one in which it was marked as deprecated.
    """

    def __init__(
        self,
        license_text: str,
        is_osi_approved: Optional[bool] = None,
        is_fsf_libre: Optional[bool] = None,
        standard_license_header: Optional[str] = None,
        standard_license_template: Optional[str] = None,
        is_deprecated_license_id: Optional[bool] = None,
        obsoleted_by: Optional[str] = None,
        list_version_added: Optional[str] = None,
        deprecated_version: Optional[str] = None,
    ):
        check_types_and_set_values(self, locals())
