# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from beartype.typing import List, Optional

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties
from spdx_tools.common.typing.type_checks import check_types_and_set_values

from ..core import CreationInfo, ExternalIdentifier, ExternalReference, IntegrityMethod
from ..licensing import AnyLicenseInfo, ExtendableLicense, LicenseAddition


@dataclass_with_properties
class WithAdditionOperator(AnyLicenseInfo):
    """
    A WithAdditionOperator indicates that the designated License is subject to the designated LicenseAddition, which
    might be a license exception on the SPDX Exceptions List (ListedLicenseException) or may be other additional text
    (CustomLicenseAddition). It is represented in the SPDX License Expression Syntax by the `WITH` operator.
    """

    subject_license: ExtendableLicense
    subject_addition: LicenseAddition

    def __init__(
        self,
        spdx_id: str,
        creation_info: CreationInfo,
        subject_license: ExtendableLicense,
        subject_addition: LicenseAddition,
        name: Optional[str] = None,
        summary: Optional[str] = None,
        description: Optional[str] = None,
        comment: Optional[str] = None,
        verified_using: List[IntegrityMethod] = None,
        external_reference: List[ExternalReference] = None,
        external_identifier: List[ExternalIdentifier] = None,
        extension: List[str] = None,
    ):
        verified_using = [] if verified_using is None else verified_using
        external_reference = [] if external_reference is None else external_reference
        external_identifier = [] if external_identifier is None else external_identifier
        extension = [] if extension is None else extension
        check_types_and_set_values(self, locals())
