# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from .conjunctive_license_set import ConjunctiveLicenseSet
from .custom_license import CustomLicense
from .custom_license_addition import CustomLicenseAddition
from .disjunctive_license_set import DisjunctiveLicenseSet
from .extendable_license import ExtendableLicense
from .license import License
from .license_addition import LicenseAddition
from .listed_license import ListedLicense
from .listed_license_exception import ListedLicenseException
from .or_later_operator import OrLaterOperator
from .with_addition_operator import WithAdditionOperator
