# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_python_model_from_spec.py
# Do not manually edit!
# flake8: noqa

from beartype.typing import List, Optional

from spdx_tools.common.typing.dataclass_with_properties import dataclass_with_properties
from spdx_tools.common.typing.type_checks import check_types_and_set_values

from ..core.creation_info import CreationInfo
from ..core.external_identifier import ExternalIdentifier
from ..core.external_reference import ExternalReference
from ..core.integrity_method import IntegrityMethod
from ..expanded_licensing.extendable_license import ExtendableLicense
from ..expanded_licensing.license_addition import LicenseAddition
from ..simple_licensing.any_license_info import AnyLicenseInfo


@dataclass_with_properties
class WithAdditionOperator(AnyLicenseInfo):
    """
    A WithAdditionOperator indicates that the designated License is subject to the designated LicenseAddition, which
    might be a license exception on the SPDX Exceptions List (ListedLicenseException) or may be other additional text
    (CustomLicenseAddition). It is represented in the SPDX License Expression Syntax by the `WITH` operator.
    """

    subject_license: ExtendableLicense = None
    """
    A subjectLicense is a License which is subject to either an 'or later' effect (OrLaterOperator) or a 'with
    additional text' effect (WithAdditionOperator).
    """
    subject_addition: LicenseAddition = None
    """
    A subjectAddition is a LicenseAddition which is subject to a 'with additional text' effect (WithAdditionOperator).
    """

    def __init__(
        self,
        spdx_id: str,
        creation_info: CreationInfo,
        subject_license: ExtendableLicense,
        subject_addition: LicenseAddition,
        name: Optional[str] = None,
        summary: Optional[str] = None,
        description: Optional[str] = None,
        comment: Optional[str] = None,
        verified_using: List[IntegrityMethod] = None,
        external_reference: List[ExternalReference] = None,
        external_identifier: List[ExternalIdentifier] = None,
        extension: List[str] = None,
    ):
        verified_using = [] if verified_using is None else verified_using
        external_reference = [] if external_reference is None else external_reference
        external_identifier = [] if external_identifier is None else external_identifier
        extension = [] if extension is None else extension
        check_types_and_set_values(self, locals())
