# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_model_to_rdf.py
# Do not manually edit!
# flake8: noqa
# isort:skip_file

# fmt: off

from rdflib import Graph, URIRef, RDF, Literal, BNode
from rdflib.term import Identifier
from spdx_tools.spdx.casing_tools import snake_case_to_camel_case
from . import expanded_licensing, core, dataset, ai, security, build, software, simple_licensing


def positive_integer_range_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/PositiveIntegerRange")
    graph.add((element_node, RDF.type, type_node))
    positive_integer_range_properties_to_rdf(element_node, obj, graph)
    return element_node


def positive_integer_range_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.begin is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/begin")
        value = obj.begin
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#positiveInteger")))
    if obj.end is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/end")
        value = obj.end
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#positiveInteger")))


def element_collection_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/ElementCollection")
    graph.add((element_node, RDF.type, type_node))
    element_collection_properties_to_rdf(element_node, obj, graph)
    return element_node


def element_collection_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    for value in obj.element:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/element")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.root_element:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/rootElement")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.imports:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/imports")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    core.element_properties_to_rdf(node, obj, graph)


def external_reference_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/ExternalReference")
    graph.add((element_node, RDF.type, type_node))
    external_reference_properties_to_rdf(element_node, obj, graph)
    return element_node


def external_reference_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.external_reference_type is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/externalReferenceType")
        value = obj.external_reference_type
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.locator:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/locator")
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#anyURI")))
    if obj.content_type is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/contentType")
        value = obj.content_type
        graph.add((node, prop_node, Literal(value, datatype="https://spdx.org/rdf/v3/Core/MediaType")))
    if obj.comment is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/comment")
        value = obj.comment
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))


def external_identifier_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/ExternalIdentifier")
    graph.add((element_node, RDF.type, type_node))
    external_identifier_properties_to_rdf(element_node, obj, graph)
    return element_node


def external_identifier_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.external_identifier_type is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/externalIdentifierType")
        value = obj.external_identifier_type
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    if obj.identifier is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/identifier")
        value = obj.identifier
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.comment is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/comment")
        value = obj.comment
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    for value in obj.identifier_locator:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/identifierLocator")
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#anyURI")))
    if obj.issuing_authority is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/issuingAuthority")
        value = obj.issuing_authority
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#anyURI")))


def bom_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Bom")
    graph.add((element_node, RDF.type, type_node))
    bom_properties_to_rdf(element_node, obj, graph)
    return element_node


def bom_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    core.bundle_properties_to_rdf(node, obj, graph)


def spdx_document_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/SpdxDocument")
    graph.add((element_node, RDF.type, type_node))
    spdx_document_properties_to_rdf(element_node, obj, graph)
    return element_node


def spdx_document_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    core.bundle_properties_to_rdf(node, obj, graph)


def tool_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Tool")
    graph.add((element_node, RDF.type, type_node))
    tool_properties_to_rdf(element_node, obj, graph)
    return element_node


def tool_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    core.element_properties_to_rdf(node, obj, graph)


def creation_info_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/CreationInfo")
    graph.add((element_node, RDF.type, type_node))
    creation_info_properties_to_rdf(element_node, obj, graph)
    return element_node


def creation_info_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.spec_version is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/specVersion")
        value = obj.spec_version
        graph.add((node, prop_node, Literal(value, datatype="https://spdx.org/rdf/v3/Core/SemVer")))
    if obj.comment is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/comment")
        value = obj.comment
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.created is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/created")
        value = obj.created
        graph.add((node, prop_node, Literal(value, datatype="https://spdx.org/rdf/v3/Core/DateTime")))
    for value in obj.created_by:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/createdBy")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.created_using:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/createdUsing")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.profile:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/profile")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    if obj.data_license is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/dataLicense")
        value = obj.data_license
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))


def organization_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Organization")
    graph.add((element_node, RDF.type, type_node))
    organization_properties_to_rdf(element_node, obj, graph)
    return element_node


def organization_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    core.agent_properties_to_rdf(node, obj, graph)


def lifecycle_scoped_relationship_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/LifecycleScopedRelationship")
    graph.add((element_node, RDF.type, type_node))
    lifecycle_scoped_relationship_properties_to_rdf(element_node, obj, graph)
    return element_node


def lifecycle_scoped_relationship_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.scope is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/scope")
        value = obj.scope
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    core.relationship_properties_to_rdf(node, obj, graph)


def software_agent_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/SoftwareAgent")
    graph.add((element_node, RDF.type, type_node))
    software_agent_properties_to_rdf(element_node, obj, graph)
    return element_node


def software_agent_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    core.agent_properties_to_rdf(node, obj, graph)


def integrity_method_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/IntegrityMethod")
    graph.add((element_node, RDF.type, type_node))
    integrity_method_properties_to_rdf(element_node, obj, graph)
    return element_node


def integrity_method_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.comment is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/comment")
        value = obj.comment
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))


def relationship_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Relationship")
    graph.add((element_node, RDF.type, type_node))
    relationship_properties_to_rdf(element_node, obj, graph)
    return element_node


def relationship_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.from_element is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/from")
        value = obj.from_element
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.to:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/to")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    if obj.relationship_type is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/relationshipType")
        value = obj.relationship_type
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    if obj.completeness is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/completeness")
        value = obj.completeness
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    if obj.start_time is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/startTime")
        value = obj.start_time
        graph.add((node, prop_node, Literal(value, datatype="https://spdx.org/rdf/v3/Core/DateTime")))
    if obj.end_time is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/endTime")
        value = obj.end_time
        graph.add((node, prop_node, Literal(value, datatype="https://spdx.org/rdf/v3/Core/DateTime")))
    core.element_properties_to_rdf(node, obj, graph)


def element_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Element")
    graph.add((element_node, RDF.type, type_node))
    element_properties_to_rdf(element_node, obj, graph)
    return element_node


def element_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.name is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/name")
        value = obj.name
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.summary is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/summary")
        value = obj.summary
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.description is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/description")
        value = obj.description
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.comment is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/comment")
        value = obj.comment
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.creation_info is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/creationInfo")
        value = obj.creation_info
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.verified_using:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/verifiedUsing")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.external_reference:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/externalReference")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.external_identifier:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/externalIdentifier")
        graph.add((node, prop_node, model_to_rdf(value, graph)))


def agent_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Agent")
    graph.add((element_node, RDF.type, type_node))
    agent_properties_to_rdf(element_node, obj, graph)
    return element_node


def agent_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    core.element_properties_to_rdf(node, obj, graph)


def hash_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Hash")
    graph.add((element_node, RDF.type, type_node))
    hash_properties_to_rdf(element_node, obj, graph)
    return element_node


def hash_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.algorithm is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/algorithm")
        value = obj.algorithm
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    if obj.hash_value is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/hashValue")
        value = obj.hash_value
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    core.integrity_method_properties_to_rdf(node, obj, graph)


def dictionary_entry_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/DictionaryEntry")
    graph.add((element_node, RDF.type, type_node))
    dictionary_entry_properties_to_rdf(element_node, obj, graph)
    return element_node


def dictionary_entry_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.key is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/key")
        value = obj.key
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.value is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/value")
        value = obj.value
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))


def person_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Person")
    graph.add((element_node, RDF.type, type_node))
    person_properties_to_rdf(element_node, obj, graph)
    return element_node


def person_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    core.agent_properties_to_rdf(node, obj, graph)


def bundle_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Bundle")
    graph.add((element_node, RDF.type, type_node))
    bundle_properties_to_rdf(element_node, obj, graph)
    return element_node


def bundle_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.context is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/context")
        value = obj.context
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    core.element_collection_properties_to_rdf(node, obj, graph)


def artifact_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Artifact")
    graph.add((element_node, RDF.type, type_node))
    artifact_properties_to_rdf(element_node, obj, graph)
    return element_node


def artifact_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    for value in obj.originated_by:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/originatedBy")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.supplied_by:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/suppliedBy")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    if obj.built_time is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/builtTime")
        value = obj.built_time
        graph.add((node, prop_node, Literal(value, datatype="https://spdx.org/rdf/v3/Core/DateTime")))
    if obj.release_time is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/releaseTime")
        value = obj.release_time
        graph.add((node, prop_node, Literal(value, datatype="https://spdx.org/rdf/v3/Core/DateTime")))
    if obj.valid_until_time is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/validUntilTime")
        value = obj.valid_until_time
        graph.add((node, prop_node, Literal(value, datatype="https://spdx.org/rdf/v3/Core/DateTime")))
    for value in obj.standard:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/standard")
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    core.element_properties_to_rdf(node, obj, graph)


def annotation_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/Annotation")
    graph.add((element_node, RDF.type, type_node))
    annotation_properties_to_rdf(element_node, obj, graph)
    return element_node


def annotation_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.annotation_type is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/annotationType")
        value = obj.annotation_type
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    for value in obj.content_type:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/contentType")
        graph.add((node, prop_node, Literal(value, datatype="https://spdx.org/rdf/v3/Core/MediaType")))
    if obj.statement is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/statement")
        value = obj.statement
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.subject is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/subject")
        value = obj.subject
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    core.element_properties_to_rdf(node, obj, graph)


def external_map_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Core/ExternalMap")
    graph.add((element_node, RDF.type, type_node))
    external_map_properties_to_rdf(element_node, obj, graph)
    return element_node


def external_map_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.external_id is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/externalId")
        value = obj.external_id
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#anyURI")))
    for value in obj.verified_using:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/verifiedUsing")
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    if obj.location_hint is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/locationHint")
        value = obj.location_hint
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#anyURI")))
    if obj.defining_document is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Core/definingDocument")
        value = obj.defining_document
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#anyURI")))


def relationship_completeness_to_rdf(obj, graph: Graph) -> Identifier:
    from .converter import enum_value_to_str
    name = enum_value_to_str(obj)
    return URIRef("https://spdx.org/rdf/v3/Core/RelationshipCompleteness/" + name)


def profile_identifier_type_to_rdf(obj, graph: Graph) -> Identifier:
    from .converter import enum_value_to_str
    name = enum_value_to_str(obj)
    return URIRef("https://spdx.org/rdf/v3/Core/ProfileIdentifierType/" + name)


def external_identifier_type_to_rdf(obj, graph: Graph) -> Identifier:
    from .converter import enum_value_to_str
    name = enum_value_to_str(obj)
    return URIRef("https://spdx.org/rdf/v3/Core/ExternalIdentifierType/" + name)


def external_reference_type_to_rdf(obj, graph: Graph) -> Identifier:
    from .converter import enum_value_to_str
    name = enum_value_to_str(obj)
    return URIRef("https://spdx.org/rdf/v3/Core/ExternalReferenceType/" + name)


def lifecycle_scope_type_to_rdf(obj, graph: Graph) -> Identifier:
    from .converter import enum_value_to_str
    name = enum_value_to_str(obj)
    return URIRef("https://spdx.org/rdf/v3/Core/LifecycleScopeType/" + name)


def annotation_type_to_rdf(obj, graph: Graph) -> Identifier:
    from .converter import enum_value_to_str
    name = enum_value_to_str(obj)
    return URIRef("https://spdx.org/rdf/v3/Core/AnnotationType/" + name)


def hash_algorithm_to_rdf(obj, graph: Graph) -> Identifier:
    from .converter import enum_value_to_str
    name = enum_value_to_str(obj)
    return URIRef("https://spdx.org/rdf/v3/Core/HashAlgorithm/" + name)


def relationship_type_to_rdf(obj, graph: Graph) -> Identifier:
    from .converter import enum_value_to_str
    name = enum_value_to_str(obj)
    return URIRef("https://spdx.org/rdf/v3/Core/RelationshipType/" + name)


# fmt: on
