# SPDX-License-Identifier: Apache-2.0
#
# This file was auto-generated by dev/gen_model_to_rdf.py
# Do not manually edit!
# flake8: noqa
# isort:skip_file

# fmt: off

from rdflib import Graph, URIRef, RDF, Literal, BNode
from rdflib.term import Identifier
from spdx_tools.spdx.casing_tools import snake_case_to_camel_case
from . import expanded_license, core, dataset, licensing, ai, security, build, software


def listed_license_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Licensing/ListedLicense")
    graph.add((element_node, RDF.type, type_node))
    listed_license_properties_to_rdf(element_node, obj, graph)
    return element_node


def listed_license_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.list_version_added is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/listVersionAdded")
        value = obj.list_version_added
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.deprecated_version is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/deprecatedVersion")
        value = obj.deprecated_version
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    licensing.license_properties_to_rdf(node, obj, graph)


def with_addition_operator_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Licensing/WithAdditionOperator")
    graph.add((element_node, RDF.type, type_node))
    with_addition_operator_properties_to_rdf(element_node, obj, graph)
    return element_node


def with_addition_operator_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.subject_license is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/ExpandedLicense/subjectLicense")
        value = obj.subject_license
        graph.add((node, prop_node, Literal(value, datatype="https://spdx.org/rdf/v3/Licensing/ExtendableLicense")))
    if obj.subject_addition is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/ExpandedLicense/subjectAddition")
        value = obj.subject_addition
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    licensing.any_license_info_properties_to_rdf(node, obj, graph)


def license_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Licensing/License")
    graph.add((element_node, RDF.type, type_node))
    license_properties_to_rdf(element_node, obj, graph)
    return element_node


def license_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.license_text is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/licenseText")
        value = obj.license_text
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.is_osi_approved is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/isOsiApproved")
        value = obj.is_osi_approved
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#boolean")))
    if obj.is_fsf_libre is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/isFsfLibre")
        value = obj.is_fsf_libre
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#boolean")))
    if obj.standard_license_header is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/standardLicenseHeader")
        value = obj.standard_license_header
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.standard_license_template is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/standardLicenseTemplate")
        value = obj.standard_license_template
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.is_deprecated_license_id is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/isDeprecatedLicenseId")
        value = obj.is_deprecated_license_id
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#boolean")))
    if obj.obsoleted_by is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/obsoletedBy")
        value = obj.obsoleted_by
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    licensing.extendable_license_properties_to_rdf(node, obj, graph)


def custom_license_addition_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Licensing/CustomLicenseAddition")
    graph.add((element_node, RDF.type, type_node))
    custom_license_addition_properties_to_rdf(element_node, obj, graph)
    return element_node


def custom_license_addition_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    licensing.license_addition_properties_to_rdf(node, obj, graph)


def license_addition_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Licensing/LicenseAddition")
    graph.add((element_node, RDF.type, type_node))
    license_addition_properties_to_rdf(element_node, obj, graph)
    return element_node


def license_addition_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.addition_text is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/additionText")
        value = obj.addition_text
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.standard_addition_template is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/standardAdditionTemplate")
        value = obj.standard_addition_template
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.is_deprecated_addition_id is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/isDeprecatedAdditionId")
        value = obj.is_deprecated_addition_id
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#boolean")))
    if obj.obsoleted_by is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/obsoletedBy")
        value = obj.obsoleted_by
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    core.element_properties_to_rdf(node, obj, graph)


def or_later_operator_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Licensing/OrLaterOperator")
    graph.add((element_node, RDF.type, type_node))
    or_later_operator_properties_to_rdf(element_node, obj, graph)
    return element_node


def or_later_operator_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.subject_license is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/ExpandedLicense/subjectLicense")
        value = obj.subject_license
        graph.add((node, prop_node, model_to_rdf(value, graph)))
    licensing.extendable_license_properties_to_rdf(node, obj, graph)


def custom_license_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Licensing/CustomLicense")
    graph.add((element_node, RDF.type, type_node))
    custom_license_properties_to_rdf(element_node, obj, graph)
    return element_node


def custom_license_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    licensing.license_properties_to_rdf(node, obj, graph)


def license_expression_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Licensing/LicenseExpression")
    graph.add((element_node, RDF.type, type_node))
    license_expression_properties_to_rdf(element_node, obj, graph)
    return element_node


def license_expression_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.license_expression is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/licenseExpression")
        value = obj.license_expression
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    licensing.any_license_info_properties_to_rdf(node, obj, graph)


def listed_license_exception_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Licensing/ListedLicenseException")
    graph.add((element_node, RDF.type, type_node))
    listed_license_exception_properties_to_rdf(element_node, obj, graph)
    return element_node


def listed_license_exception_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    if obj.list_version_added is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/listVersionAdded")
        value = obj.list_version_added
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    if obj.deprecated_version is not None:
        prop_node = URIRef("https://spdx.org/rdf/v3/Licensing/deprecatedVersion")
        value = obj.deprecated_version
        graph.add((node, prop_node, Literal(value, datatype="http://www.w3.org/2001/XMLSchema#string")))
    licensing.license_addition_properties_to_rdf(node, obj, graph)


def any_license_info_to_rdf(obj, graph: Graph) -> Identifier:
    if '_spdx_id' in obj.__dict__:
        element_node = URIRef(obj.spdx_id)
    else:
        element_node = BNode()
    type_node = URIRef("https://spdx.org/rdf/v3/Licensing/AnyLicenseInfo")
    graph.add((element_node, RDF.type, type_node))
    any_license_info_properties_to_rdf(element_node, obj, graph)
    return element_node


def any_license_info_properties_to_rdf(node: Identifier, obj, graph: Graph):
    from .converter import model_to_rdf
    core.element_properties_to_rdf(node, obj, graph)


# fmt: on
